# Generated by Django 3.2.8 on 2021-10-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakeCake', '0003_auto_20211026_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='order_status',
            field=models.BooleanField(choices=[(True, 'Готовим ваш торт'), (False, 'Торт в пути'), (None, 'Торт у вас')], null=True, verbose_name='Статус заказа'),
        ),
    ]
