# Generated by Django 3.2.8 on 2021-10-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakeCake', '0005_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Заказы', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='order_status',
        ),
        migrations.AddField(
            model_name='message',
            name='berries',
            field=models.TextField(blank=True, verbose_name='Ягоды'),
        ),
        migrations.AddField(
            model_name='message',
            name='decor',
            field=models.TextField(blank=True, verbose_name='Декор'),
        ),
        migrations.AddField(
            model_name='message',
            name='form',
            field=models.TextField(blank=True, verbose_name='Форма'),
        ),
        migrations.AddField(
            model_name='message',
            name='number_levels',
            field=models.TextField(blank=True, verbose_name='Количество уровней'),
        ),
        migrations.AddField(
            model_name='message',
            name='order_status',
            field=models.BooleanField(choices=[(True, 'Готовим ваш торт'), (False, 'Торт в пути'), (None, 'Торт у вас')], null=True, verbose_name='Статус заказа'),
        ),
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.TextField(blank=True, verbose_name='Надпись'),
        ),
        migrations.AddField(
            model_name='message',
            name='topping',
            field=models.TextField(blank=True, verbose_name='Топпинг'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
