# Generated by Django 3.2.8 on 2021-10-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakeCake', '0006_auto_20211026_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='berries',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='decor',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='form',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='number_levels',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='title',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='topping',
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.TextField(blank=True, verbose_name='Имя пользователя'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.TextField(blank=True, verbose_name='Фамилия пользователя'),
        ),
        migrations.AlterField(
            model_name='message',
            name='order_status',
            field=models.BooleanField(choices=[(None, 'Готовим ваш торт'), (False, 'Торт в пути'), (True, 'Торт у вас')], null=True, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(verbose_name='Псевдоним'),
        ),
    ]
