# Generated by Django 3.2.8 on 2021-10-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakeCake', '0007_auto_20211026_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='message',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AddField(
            model_name='message',
            name='delivery_date',
            field=models.TextField(blank=True, verbose_name='Дата доставки'),
        ),
        migrations.AddField(
            model_name='message',
            name='delivery_time',
            field=models.TextField(blank=True, verbose_name='Время доставки'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='external_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='ID пользователя в сети'),
        ),
    ]
