# Generated by Django 3.2.8 on 2021-10-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakeCake', '0008_auto_20211027_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.TextField(blank=True, verbose_name='Телефон пользователя'),
        ),
    ]
