# Generated by Django 3.2.8 on 2021-10-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakeCake', '0009_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='address',
            field=models.CharField(blank=True, max_length=50, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='message',
            name='berries',
            field=models.CharField(blank=True, max_length=10, verbose_name='Ягоды'),
        ),
        migrations.AlterField(
            model_name='message',
            name='comment',
            field=models.TextField(blank=True, max_length=200, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='message',
            name='decor',
            field=models.CharField(blank=True, max_length=10, verbose_name='Декор'),
        ),
        migrations.AlterField(
            model_name='message',
            name='delivery_date',
            field=models.CharField(blank=True, max_length=20, verbose_name='Дата доставки'),
        ),
        migrations.AlterField(
            model_name='message',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=20, verbose_name='Время доставки'),
        ),
        migrations.AlterField(
            model_name='message',
            name='form',
            field=models.CharField(blank=True, max_length=10, verbose_name='Форма'),
        ),
        migrations.AlterField(
            model_name='message',
            name='number_levels',
            field=models.CharField(blank=True, max_length=1, verbose_name='Количество уровней'),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.TextField(blank=True, max_length=20, verbose_name='Надпись'),
        ),
        migrations.AlterField(
            model_name='message',
            name='topping',
            field=models.CharField(blank=True, max_length=10, verbose_name='Топпинг'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=10, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=10, verbose_name='Фамилия пользователя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Псевдоним'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон пользователя'),
        ),
    ]
