# Generated by Django 3.2.8 on 2021-10-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakeCake', '0012_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='without_topping',
            field=models.IntegerField(blank=True, null=True, verbose_name='Без топпинга'),
        ),
        migrations.AlterField(
            model_name='price',
            name='level_1',
            field=models.IntegerField(default=10000, verbose_name='1 уровень'),
        ),
        migrations.AlterField(
            model_name='price',
            name='white_syrup',
            field=models.IntegerField(blank=True, verbose_name='Белый соус'),
        ),
    ]
