# Generated by Django 3.2.8 on 2021-10-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakeCake', '0014_alter_price_without_topping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='without_topping',
            field=models.IntegerField(default=0, verbose_name='Без топпинга'),
        ),
    ]
