# Generated by Django 3.2.8 on 2021-10-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakeCake', '0015_alter_price_without_topping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='blackberry',
            field=models.IntegerField(default=400, verbose_name='Ежевика'),
        ),
        migrations.AlterField(
            model_name='price',
            name='blueberry',
            field=models.IntegerField(default=450, verbose_name='Голубика'),
        ),
        migrations.AlterField(
            model_name='price',
            name='blueberry_syrup',
            field=models.IntegerField(default=350, verbose_name='Черничный сироп'),
        ),
        migrations.AlterField(
            model_name='price',
            name='caramel_syrup',
            field=models.IntegerField(default=180, verbose_name='Карамельный сироп'),
        ),
        migrations.AlterField(
            model_name='price',
            name='circle',
            field=models.IntegerField(default=400, verbose_name='Круг'),
        ),
        migrations.AlterField(
            model_name='price',
            name='hazelnuts',
            field=models.IntegerField(default=350, verbose_name='Фундук'),
        ),
        migrations.AlterField(
            model_name='price',
            name='level_1',
            field=models.IntegerField(default=400, verbose_name='1 уровень'),
        ),
        migrations.AlterField(
            model_name='price',
            name='level_2',
            field=models.IntegerField(default=750, verbose_name='2 уровень'),
        ),
        migrations.AlterField(
            model_name='price',
            name='level_3',
            field=models.IntegerField(default=1100, verbose_name='3 уровень'),
        ),
        migrations.AlterField(
            model_name='price',
            name='maple_syrup',
            field=models.IntegerField(default=200, verbose_name='Кленовый сироп'),
        ),
        migrations.AlterField(
            model_name='price',
            name='marshmallow',
            field=models.IntegerField(default=200, verbose_name='Маршмеллоу'),
        ),
        migrations.AlterField(
            model_name='price',
            name='marzipan',
            field=models.IntegerField(default=280, verbose_name='Марципан'),
        ),
        migrations.AlterField(
            model_name='price',
            name='meringue',
            field=models.IntegerField(default=400, verbose_name='Безе'),
        ),
        migrations.AlterField(
            model_name='price',
            name='milk_chocolate',
            field=models.IntegerField(default=200, verbose_name='Молочный шоколад'),
        ),
        migrations.AlterField(
            model_name='price',
            name='pecan',
            field=models.IntegerField(default=300, verbose_name='Пекан'),
        ),
        migrations.AlterField(
            model_name='price',
            name='pistachios',
            field=models.IntegerField(default=300, verbose_name='Фисташки'),
        ),
        migrations.AlterField(
            model_name='price',
            name='raspberry',
            field=models.IntegerField(default=300, verbose_name='Малина'),
        ),
        migrations.AlterField(
            model_name='price',
            name='rectangle',
            field=models.IntegerField(default=1000, verbose_name='Прямоугольник'),
        ),
        migrations.AlterField(
            model_name='price',
            name='square',
            field=models.IntegerField(default=600, verbose_name='Квадрат'),
        ),
        migrations.AlterField(
            model_name='price',
            name='strawberry',
            field=models.IntegerField(default=500, verbose_name='Клубника '),
        ),
        migrations.AlterField(
            model_name='price',
            name='strawberry_syrup',
            field=models.IntegerField(default=300, verbose_name='Клубничный сироп'),
        ),
        migrations.AlterField(
            model_name='price',
            name='title',
            field=models.IntegerField(default=500, verbose_name='Надпись'),
        ),
        migrations.AlterField(
            model_name='price',
            name='white_syrup',
            field=models.IntegerField(default=200, verbose_name='Белый соус'),
        ),
    ]
