# Generated by Django 3.2.8 on 2021-10-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakeCake', '0017_auto_20211029_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='text',
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='price',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='price',
            name='level_1',
            field=models.IntegerField(default=400, verbose_name='Один уровень'),
        ),
        migrations.AlterField(
            model_name='price',
            name='level_2',
            field=models.IntegerField(default=750, verbose_name='Два уровня'),
        ),
        migrations.AlterField(
            model_name='price',
            name='level_3',
            field=models.IntegerField(default=1100, verbose_name='Три уровня'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
